spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      # defaultZone: http://service-registry:9000/eureka
      defaultZone: http://localhost:9000/eureka

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  prefix: /api
  routes:
    cat:
      path: /cat/**
      serviceId: cats
    country:
      path: /country/**
      serviceId: countries
    userInfo:
      path: /about/**
      serviceId: usersinfo
      
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
